# Generated by Django 3.2.4 on 2021-08-03 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('frameid', models.BigIntegerField()),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('top10_palette', models.CharField(blank=True, max_length=100, null=True)),
                ('kmeans_palette', models.CharField(blank=True, max_length=100, null=True)),
                ('random_palette', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Frame',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('top10_palette', models.CharField(blank=True, max_length=100, null=True)),
                ('kmeans_palette', models.CharField(blank=True, max_length=100, null=True)),
                ('random_palette', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('cb_status', models.CharField(blank=True, max_length=20, null=True)),
                ('media_industry', models.TextField(blank=True, null=True)),
                ('seen_history', models.TextField(blank=True, null=True)),
                ('single_choise', models.CharField(blank=True, max_length=20, null=True)),
                ('multi_choice', models.CharField(blank=True, max_length=20, null=True)),
                ('movieid', models.ForeignKey(db_column='movieid', on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
                ('single_frameid', models.ForeignKey(db_column='single_frameid', on_delete=django.db.models.deletion.CASCADE, to='main.frame')),
            ],
            options={
                'db_table': 'Participate',
            },
        ),
        migrations.AddField(
            model_name='frame',
            name='movieid',
            field=models.ForeignKey(db_column='movieid', on_delete=django.db.models.deletion.CASCADE, to='main.movie'),
        ),
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together={('movieid', 'frameid')},
        ),
    ]
