# Generated by Django 3.2.4 on 2021-09-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_frame_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='kmeans_palette',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='random_palette',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='top10_palette',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
