# Generated by Django 3.2.4 on 2021-09-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210901_0148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participate',
            new_name='Participant',
        ),
        migrations.AlterField(
            model_name='frame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='kmeans_palette',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='random_palette',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='top10_palette',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
