# Generated by Django 3.2.4 on 2021-09-12 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210912_2218'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participant',
            table='Participant',
        ),
    ]
